### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by danielmellado** [codegram/vim-codereview#11]
I'm getting this error while trying to do a codereview

Error detected while processing function codereview#Review:
line    1:
NoMethodError: undefined method `[]' for nil:NilClass

**Comment by apporc** [comment]
I met this problem too, it's because the first time i did not give it a valid token.
Just delete ~/.codereview and restart CodeReivew and give a right token, it is ok then.

**Comment by jonsyu1** [comment]
I'm attempting to use this plugin in a github enterprise environment. Is this not supported? If so, can we update the issue or create a new issue to reflect this?

**Comment by sparky005** [comment]
I am also getting this error on Windows. I am trying to get at a corporate Github instance (GH enterprise.) I am certainly my API token is valid. Is this a known issue with Enterprise?

**Comment by sparky005** [comment]
I think the issue in my case is that we have HTTP disabled in my org, forcing use of SSH keys only (API keys should still be an option.) Is this plugin checking out via HTTP? Is there a way to force SSH?

**Comment by jamietanna** [comment]
I can confirm that this does not work out of the box with GitHub Enterprise. The fixes can be made to:

- https://github.com/codegram/vim-codereview/blob/master/lib/github.rb#L98
- https://github.com/codegram/vim-codereview/blob/master/lib/github.rb#L103

I will raise a PR shortly to make it possible to configure this via a configuration variable.
